name: Update Github Stats

on:
  schedule:
    - cron: "47 2 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v4
      
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install requirements
        run: npm install

      - name: Github Configurations
        run: |
          git config --global user.name "Github Actions"
          git config --global user.email "action@github.com"
          git pull
          
      - name: Update Template
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Используем встроенный токен вместо кастомного
        run: |
          echo "Running updater..."
          node updater.js ${{ github.repository_owner }} dracula $GITHUB_TOKEN

      - name: Commit and push changes
        run: |
          git add .
          git diff --quiet && git diff --staged --quiet || git commit -m "Github Stats updated 🎉"
          git push
